#include "camera_lens_table.hpp"

#include <format>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <glm/glm.hpp>

#include "core/ecs/components/camera.hpp"
#include "core/ecs/components/component.hpp"
#include "core/ecs/registry.hpp"
#include "core/shader_plugin/glsl_codegen.hpp"
#include "core/shader_plugin/shader_plugin.hpp"

namespace {

constexpr const char* kTiltShiftPath = "assets/camera/tilt_shift.glsl";

ShaderPlugin& tiltShiftPlugin() {
    static ShaderPlugin plugin;
    plugin.parse(kTiltShiftPath, CameraLensTable::kType, CameraLensTable::kVersion, CameraLensTable::slotFor(kTiltShiftPath));
    return plugin;
}

} // namespace

int CameraLensTable::slotFor(const std::filesystem::path& path) {
    static std::unordered_map<std::filesystem::path, int> slots;
    const auto [it, inserted] = slots.try_emplace(path, static_cast<int>(slots.size()));
    return it->second;
}

int CameraLensTable::pack(ecs::Registry& registry, ecs::Entity camera, std::vector<float>& params) {
    if (registry.has(camera, ecs::CameraLensPlugin)) {
        ecs::Component& c = registry.get(camera, ecs::CameraLensPlugin);
        ShaderPlugin& plugin = c.payload<ShaderPlugin>("plugin");
        const std::filesystem::path path = c.get<std::filesystem::path>("path");
        plugin.parse(path, kType, kVersion, slotFor(path));
        if (plugin.getError().empty()) {
            const std::vector<float> values = plugin.packValues();
            params.insert(params.end(), values.begin(), values.end());
            return plugin.getSlot();
        }
        return -1;
    }

    if (registry.has(camera, ecs::TiltShiftLens)) {
        ShaderPlugin& plugin = tiltShiftPlugin();
        if (!plugin.getError().empty()) return -1;

        const ecs::Component& ts = registry.get(camera, ecs::TiltShiftLens);
        const glm::vec3 planePosition = ts.get<glm::vec3>("plane_position");
        const glm::vec3 planeRotation = ts.get<glm::vec3>("plane_rotation");
        const std::vector<float> values = {
            planePosition.x, planePosition.y, planePosition.z,
            planeRotation.x, planeRotation.y, planeRotation.z,
            ts.get<float>("shift_x"), ts.get<float>("shift_y"),
        };
        params.insert(params.end(), values.begin(), values.end());
        return plugin.getSlot();
    }

    return -1;
}

void CameraLensTable::generateDispatch() {
    tiltShiftPlugin();

    std::string functions;
    std::string cases;
    std::unordered_set<int> emittedSlots;

    for (ShaderPlugin* plugin : ShaderPlugin::registry()) {
        if (plugin->getType() != CameraLensTable::kType) continue;
        if (!plugin->getError().empty() || plugin->getBody().empty()) continue;
        if (!emittedSlots.insert(plugin->getSlot()).second) continue;

        const std::string funcName = plugin->getPrefix() + "programmable";
        functions += std::format(
            "// ============================= {}{} =============================\n"
            "{}"
            "{}"
            "LensSample {} (int base, vec2 ndcPos, CameraPose pose, float U, float V, inout RngState rng) {{\n"
            "float lensRadius = ubo.camera.thinLens.lensRadius;\n"
            "float focalDistance = ubo.camera.thinLens.focusDistance;\n"
            "{}"
            "LensSample result;\n"
            "{}"
            "return result;\n"
            "}}\n\n",
            CameraLensTable::kType, plugin->getSlot(), GlslCodegen::declareGlobals(*plugin), plugin->getDeclarations(), funcName,
            GlslCodegen::assignParams(*plugin, [](int i) { return std::format("pluginParams.values[base+{}]", i); }),
            plugin->getBody()
        );
        cases += std::format("        case {}: return {} (base, ndcPos, pose, U, V, rng);\n", plugin->getSlot(), funcName);
    }

    std::string content = std::format(
        "// WARN: AUTO-GENERATED by CameraLensTable::generateDispatch, do not edit by hand.\n"
        "// Source: the programmable camera lens scripts loaded into the scene (see assets/camera/).\n"
        "{}\n"
        "LensSample dispatchCameraLens(int slot, int base, vec2 ndcPos, CameraPose pose, float U, float V, inout RngState rng) {{\n"
        "    switch (slot) {{\n"
        "{}"
        "    }}\n"
        "    return LensSample(pose.eye, pose.dir);\n"
        "}}\n",
        functions, cases
    );

    std::filesystem::path outputPath = "./src/shaders/generated/camera_lens_dispatch.glsl";
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);

    std::ifstream existing(outputPath);
    std::stringstream existingBuffer;
    existingBuffer << existing.rdbuf();
    if (existingBuffer.str() == content) return;

    std::ofstream(outputPath) << content;
}
