#include "compositing_table.hpp"

#include <algorithm>
#include <format>
#include <unordered_map>

#include "core/ecs/components/component.hpp"
#include "core/ecs/components/compositing.hpp"
#include "core/ecs/registry.hpp"
#include "core/scene/scene.hpp"
#include "core/shader_plugin/glsl_codegen.hpp"
#include "core/shader_plugin/shader_plugin.hpp"

namespace {
const bool registered = [] {
    ShaderPlugin::registerDispatchGenerator(&CompositingTable::generateDispatch);
    return true;
}();
} // namespace

int CompositingTable::slotFor(const std::filesystem::path& path) {
    static std::unordered_map<std::filesystem::path, int> slots;
    return GlslCodegen::slotFor(slots, path);
}

std::vector<ecs::CompositingPassEntry>& CompositingTable::passes(ecs::Registry& registry) {
    const ecs::Entity compositing = Scene::findSceneRootChild(registry, ecs::Compositing);
    if (compositing == ecs::Entity{}) {
        static std::vector<ecs::CompositingPassEntry> empty;
        return empty;
    }
    return registry.get(compositing, ecs::Compositing).payload<ecs::CompositingPasses>("passes").passes;
}

int CompositingTable::pack(ecs::CompositingPassEntry& pass, std::vector<float>& params) {
    pass.plugin->parse(pass.path, kType, kVersion, slotFor(pass.path));
    if (pass.plugin->getError().empty()) {
        const std::vector<float> values = pass.plugin->packValues();
        params.insert(params.end(), values.begin(), values.end());
        return pass.plugin->getSlot();
    }
    return -1;
}

int CompositingTable::totalDispatchCount(ecs::Registry& registry) {
    int total = 0;
    for (ecs::CompositingPassEntry& pass : passes(registry)) {
        pass.plugin->parse(pass.path, kType, kVersion, slotFor(pass.path));
        total += std::max(1, pass.plugin->getPassCount());
    }
    return total;
}

void CompositingTable::generateDispatch() {
    std::string functions;
    std::string cases;

    GlslCodegen::forEachActivePlugin(CompositingTable::kType, [&](ShaderPlugin& plugin, const std::string& funcName) {
        functions += std::format(
            "// ============================= {}{} =============================\n"
            "{}"
            "{}"
            "vec3 {} (int base, ivec2 pixelCoord, ivec2 texSize, int passId) {{\n"
            "{}"
            "vec3 result = sampleSource(pixelCoord, texSize);\n"
            "{}"
            "return result;\n"
            "}}\n\n",
            CompositingTable::kType, plugin.getSlot(), GlslCodegen::declareGlobals(plugin), plugin.getDeclarations(), funcName,
            GlslCodegen::assignParams(plugin, [](int i) { return std::format("pluginParams.values[base+{}]", i); }),
            plugin.getBody()
        );
        cases += std::format("        case {}: return {} (base, pixelCoord, texSize, passId);\n", plugin.getSlot(), funcName);
    });

    std::string content = std::format(
        "// WARN: AUTO-GENERATED by CompositingTable::generateDispatch, do not edit by hand.\n"
        "// Source: the programmable compositing pass scripts loaded into the scene (see assets/compositing/).\n"
        "{}\n"
        "vec3 dispatchCompositingPass(int slot, int base, ivec2 pixelCoord, ivec2 texSize, int passId) {{\n"
        "    switch (slot) {{\n"
        "{}"
        "    }}\n"
        "    return sampleSource(pixelCoord, texSize);\n"
        "}}\n",
        functions, cases
    );

    GlslCodegen::writeGeneratedFileIfChanged("./src/shaders/generated/compositing_dispatch.glsl", content);
}
