#include "material_table.hpp"

#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>

#include "core/ecs/components/component.hpp"
#include "core/ecs/components/material.hpp"
#include "core/scene/gpu_structs.hpp"
#include "core/shader_plugin/glsl_codegen.hpp"
#include "core/shader_plugin/shader_plugin.hpp"
#include "utils/string_utils.hpp"

namespace {

struct Entry {
    const ecs::ComponentType* type;
    std::function<std::vector<float>(ecs::Component&)> customValues;
};

std::string glslMacroName(const ecs::ComponentType& type, const Field& field) {
    std::string prefix = snakeCaseToPascalCase(type.getId());
    prefix[0] = static_cast<char>(std::tolower(prefix[0]));
    return prefix + snakeCaseToPascalCase(field.getId().string());
}

bool isPackableField(const Field& field) {
    return field.getId() != "albedo" && field.getType() == FieldType::Float;
}

bool hasAlbedoField(const ecs::ComponentType& type) {
    for (const Field& field : type.getFields())
        if (field.getId() == "albedo") return true;
    return false;
}

void packFields(ecs::Component& c, std::vector<float>& params) {
    if (hasAlbedoField(c.getType())) {
        const glm::vec3 a = c.get<glm::vec3>("albedo");
        params.push_back(a.r); params.push_back(a.g); params.push_back(a.b);
    }
    for (const Field& field : c.getType().getFields()) {
        if (!isPackableField(field)) continue;
        params.push_back(c.get<float>(field.getId()));
    }
}

const std::vector<Entry>& entries() {
    static const std::vector<Entry> table = {
        { &ecs::Principled, {} },
        { &ecs::Emissive, {} },
        { &ecs::Diffuse, {} },
        { &ecs::Metal, {} },
        { &ecs::Glossy, {} },
        { &ecs::Dielectric, {} },
        { &ecs::Volume, {} },
        { &ecs::MaterialPlugin, [](ecs::Component& c) -> std::vector<float> {
            ShaderPlugin& plugin = c.payload<ShaderPlugin>("plugin");
            const std::filesystem::path path = c.get<std::filesystem::path>("path");
            plugin.parse(path, MaterialTable::kType, MaterialTable::kVersion, MaterialTable::slotFor(path));
            std::vector<float> values{ static_cast<float>(plugin.getSlot()) };
            const std::vector<float> packed = plugin.packValues();
            values.insert(values.end(), packed.begin(), packed.end());
            return values;
        } },
    };
    return table;
}

} // namespace

int MaterialTable::slotFor(const std::filesystem::path& path) {
    static std::unordered_map<std::filesystem::path, int> slots;
    const auto [it, inserted] = slots.try_emplace(path, static_cast<int>(slots.size()));
    return it->second;
}

bool MaterialTable::pack(ecs::Registry& registry, ecs::Entity entity, GpuMaterial& gpu, std::vector<float>& params) {
    const std::vector<Entry>& table = entries();
    for (size_t i = 0; i < table.size(); i++) {
        const Entry& entry = table[i];
        if (!registry.has(entity, *entry.type)) continue;

        ecs::Component& c = registry.get(entity, *entry.type);
        gpu.type = static_cast<int>(i);
        gpu.base = static_cast<uint32_t>(params.size());

        if (entry.customValues) {
            const std::vector<float> values = entry.customValues(c);
            params.insert(params.end(), values.begin(), values.end());
            return true;
        }

        packFields(c, params);
        return true;
    }

    for (size_t i = 0; i < table.size(); i++) {
        if (table[i].type != &ecs::Diffuse) continue;
        gpu.type = static_cast<int>(i);
        gpu.base = static_cast<uint32_t>(params.size());
        ecs::Component fallback(*table[i].type);
        packFields(fallback, params);
        break;
    }
    return false;
}

void MaterialTable::generateGlsl() {
    const std::vector<Entry>& table = entries();

    std::string content = "// WARN: AUTO-GENERATED by MaterialTable::generateGlsl, do not edit by hand.\n\n";
    content += std::format("#define MATERIAL_PAYLOAD_SIZE {}\n\n", kMaterialPayloadSize);

    for (size_t i = 0; i < table.size(); i++)
        content += std::format("#define mat_{} {}\n", snakeCaseToPascalCase(table[i].type->getId()), i);
    content += "\n#define albedo(m) vec3((m).payload[0], (m).payload[1], (m).payload[2])\n\n";

    for (const Entry& entry : table) {
        if (entry.customValues) continue;

        int idx = hasAlbedoField(*entry.type) ? 3 : 0;
        for (const Field& field : entry.type->getFields()) {
            if (!isPackableField(field)) continue;
            content += std::format("#define {}(m) (m).payload[{}]\n", glslMacroName(*entry.type, field), idx++);
        }
    }

    std::filesystem::path outputPath = "./src/shaders/generated/material_types.glsl";
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);

    std::ifstream existing(outputPath);
    std::stringstream existingBuffer;
    existingBuffer << existing.rdbuf();
    if (existingBuffer.str() == content) return;

    std::ofstream(outputPath) << content;
}

void MaterialTable::generateDispatch() {
    std::string functions;
    std::string cases;
    std::unordered_set<int> emittedSlots;

    for (ShaderPlugin* plugin : ShaderPlugin::registry()) {
        if (plugin->getType() != MaterialTable::kType) continue;
        if (!plugin->getError().empty() || plugin->getBody().empty()) continue;
        if (!emittedSlots.insert(plugin->getSlot()).second) continue;

        const std::string funcName = plugin->getPrefix() + "programmable";
        functions += std::format(
            "// ============================= {}{} =============================\n"
            "{}"
            "{}"
            "ResolvedMaterial {} (int base, vec3 pos, vec2 uv, vec3 normal, vec3 wo, RngState rng, inout vec3 new_normal) {{\n"
            "{}"
            "ResolvedMaterial mat;\n"
            "{}"
            "return mat;\n"
            "}}\n\n",
            MaterialTable::kType, plugin->getSlot(), GlslCodegen::declareGlobals(*plugin), plugin->getDeclarations(), funcName,
            GlslCodegen::assignParams(*plugin, [](int i) { return std::format("pluginParams.values[base+{}]", i); }),
            plugin->getBody()
        );
        cases += std::format("        case {}: result = {} (base, pos, uv, normal, wo, rng, new_normal); break;\n", plugin->getSlot(), funcName);
    }

    std::string content = std::format(
        "// WARN: AUTO-GENERATED by MaterialTable::generateDispatch, do not edit by hand.\n"
        "// Source: the programmable material scripts loaded into the scene (see assets/materials/).\n"
        "{}\n"
        "ResolvedMaterial dispatchProgrammable(in Material mat, inout Hit hit, in vec3 wo, inout RngState rng) {{\n"
        "    vec3 pos    = hit.p;\n"
        "    vec3 normal = hit.normal;\n"
        "    vec2 uv     = hit.uv;\n"
        "    vec3 new_normal = normal;\n"
        "    int base = int(mat.base) + 1;\n"
        "    ResolvedMaterial result = DEFAULT_MATERIAL;\n"
        "    switch (int(pluginParams.values[mat.base])) {{\n"
        "{}"
        "    }}\n"
        "    hit.normal = new_normal;\n"
        "    return result;\n"
        "}}\n",
        functions, cases
    );

    std::filesystem::path outputPath = "./src/shaders/generated/programmable_dispatch.glsl";
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);

    std::ifstream existing(outputPath);
    std::stringstream existingBuffer;
    existingBuffer << existing.rdbuf();
    if (existingBuffer.str() == content) return;

    std::ofstream(outputPath) << content;
}
