#include "material_table.hpp"

#include <cctype>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <sstream>
#include <string>

#include "core/ecs/components/component.hpp"
#include "core/ecs/components/material.hpp"
#include "core/render/programmable_shader.hpp"
#include "core/scene/gpu_structs.hpp"
#include "utils/string_utils.hpp"

namespace {

struct Entry {
    const ecs::ComponentType* type;
    std::function<std::vector<float>(ecs::Component&)> customValues;
};

std::string glslMacroName(const ecs::ComponentType& type, const ecs::ComponentField& field) {
    std::string prefix = snakeCaseToPascalCase(type.getId());
    prefix[0] = static_cast<char>(std::tolower(prefix[0]));
    return prefix + snakeCaseToPascalCase(field.getId());
}

bool isPackableField(const ecs::ComponentField& field) {
    return field.getId() != "albedo" && field.getType() == FieldType::Float;
}

bool hasAlbedoField(const ecs::ComponentType& type) {
    for (const ecs::ComponentField& field : type.getFields())
        if (field.getId() == "albedo") return true;
    return false;
}

const std::vector<Entry>& entries() {
    static const std::vector<Entry> table = {
        { &ecs::Principled },
        { &ecs::Emissive },
        { &ecs::Diffuse },
        { &ecs::Metal },
        { &ecs::Glossy },
        { &ecs::Dielectric },
        { &ecs::Volume },
        { &ecs::ProgrammableMaterial, [](ecs::Component& c) -> std::vector<float> {
            ProgrammableShader& shader = c.payload<ProgrammableShader>("shader");
            shader.parse(c.get<std::filesystem::path>("path"));
            std::vector<float> values{ static_cast<float>(shader.getSlot()) };
            const std::vector<float> packed = shader.packValues();
            values.insert(values.end(), packed.begin(), packed.end());
            return values;
        } },
    };
    return table;
}

} // namespace

bool MaterialTable::pack(ecs::Registry& registry, ecs::Entity entity, GpuMaterial& gpu, std::vector<float>& params) {
    const std::vector<Entry>& table = entries();
    for (size_t i = 0; i < table.size(); i++) {
        const Entry& entry = table[i];
        if (!registry.has(entity, *entry.type)) continue;

        ecs::Component& c = registry.get(entity, *entry.type);
        gpu.type = static_cast<int>(i);
        gpu.base = static_cast<uint32_t>(params.size());

        if (entry.customValues) {
            const std::vector<float> values = entry.customValues(c);
            params.insert(params.end(), values.begin(), values.end());
            return true;
        }

        if (hasAlbedoField(*entry.type)) {
            const glm::vec3 a = c.get<glm::vec3>("albedo");
            params.push_back(a.r); params.push_back(a.g); params.push_back(a.b);
        }
        for (const ecs::ComponentField& field : entry.type->getFields()) {
            if (!isPackableField(field)) continue;
            params.push_back(c.get<float>(field.getId()));
        }
        return true;
    }
    return false;
}

void MaterialTable::generateGlsl() {
    const std::vector<Entry>& table = entries();

    std::string content = "// WARN: AUTO-GENERATED by MaterialTable::generateGlsl, do not edit by hand.\n\n";
    content += std::format("#define MATERIAL_PAYLOAD_SIZE {}\n\n", kMaterialPayloadSize);

    for (size_t i = 0; i < table.size(); i++)
        content += std::format("#define mat_{} {}\n", snakeCaseToPascalCase(table[i].type->getId()), i);
    content += "\n#define albedo(m) vec3((m).payload[0], (m).payload[1], (m).payload[2])\n\n";

    for (const Entry& entry : table) {
        if (entry.customValues) continue;

        int idx = hasAlbedoField(*entry.type) ? 3 : 0;
        for (const ecs::ComponentField& field : entry.type->getFields()) {
            if (!isPackableField(field)) continue;
            content += std::format("#define {}(m) (m).payload[{}]\n", glslMacroName(*entry.type, field), idx++);
        }
    }

    std::filesystem::path outputPath = "./src/shaders/core/materials/generated/material_types.glsl";
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);

    std::ifstream existing(outputPath);
    std::stringstream existingBuffer;
    existingBuffer << existing.rdbuf();
    if (existingBuffer.str() == content) return;

    std::ofstream(outputPath) << content;
}
