#include "sky_table.hpp"

#include <format>
#include <unordered_map>

#include "core/ecs/components/component.hpp"
#include "core/ecs/components/environment.hpp"
#include "core/ecs/registry.hpp"
#include "core/shader_plugin/glsl_codegen.hpp"
#include "core/shader_plugin/shader_plugin.hpp"

namespace {
const bool registered = [] {
    ShaderPlugin::registerDispatchGenerator(&SkyTable::generateDispatch);
    return true;
}();
} // namespace

int SkyTable::slotFor(const std::filesystem::path& path) {
    static std::unordered_map<std::filesystem::path, int> slots;
    return GlslCodegen::slotFor(slots, path);
}

bool SkyTable::pack(ecs::Registry& registry, ecs::Entity environment, std::vector<float>& params) {
    if (environment == ecs::Entity{} || !registry.has(environment, ecs::SkyPlugin)) return false;

    ecs::Component& c = registry.get(environment, ecs::SkyPlugin);
    ShaderPlugin& plugin = c.payload<ShaderPlugin>("plugin");
    const std::filesystem::path path = c.get<std::filesystem::path>("path");
    plugin.parse(path, kType, kVersion, slotFor(path));
    if (!plugin.getError().empty()) return false;

    const std::vector<float> values = plugin.packValues();
    params.insert(params.end(), values.begin(), values.end());
    return true;
}

void SkyTable::generateDispatch() {
    ShaderPlugin* active = GlslCodegen::findActivePlugin(SkyTable::kType);

    std::string body = active
        ? std::format(
            "// ============================= {} =============================\n"
            "{}"
            "{}"
            "vec3 dispatchSky(int base, vec3 dir) {{\n"
            "{}"
            "vec3 result = vec3(0.1);\n"
            "{}"
            "return result;\n"
            "}}\n",
            SkyTable::kType, GlslCodegen::declareGlobals(*active), active->getDeclarations(),
            GlslCodegen::assignParams(*active, [](int i) { return std::format("pluginParams.values[base+{}]", i); }),
            active->getBody()
        )
        : "vec3 dispatchSky(int base, vec3 dir) {\n    return vec3(0.1);\n}\n";

    std::string content = std::format(
        "// WARN: AUTO-GENERATED by SkyTable::generateDispatch, do not edit by hand.\n"
        "// Source: the programmable sky script on the scene's Environment entity (see assets/environment/).\n"
        "{}",
        body
    );

    GlslCodegen::writeGeneratedFileIfChanged("./src/shaders/generated/sky_dispatch.glsl", content);
}
