#include "sky_table.hpp"

#include <format>
#include <fstream>
#include <sstream>
#include <unordered_map>

#include "core/ecs/components/component.hpp"
#include "core/ecs/components/environment.hpp"
#include "core/ecs/registry.hpp"
#include "core/shader_plugin/glsl_codegen.hpp"
#include "core/shader_plugin/shader_plugin.hpp"

int SkyTable::slotFor(const std::filesystem::path& path) {
    static std::unordered_map<std::filesystem::path, int> slots;
    const auto [it, inserted] = slots.try_emplace(path, static_cast<int>(slots.size()));
    return it->second;
}

void SkyTable::pack(ecs::Registry& registry, ecs::Entity environment, std::vector<float>& params) {
    if (environment == ecs::Entity{} || !registry.has(environment, ecs::SkyPlugin)) return;

    ecs::Component& c = registry.get(environment, ecs::SkyPlugin);
    ShaderPlugin& plugin = c.payload<ShaderPlugin>("plugin");
    const std::filesystem::path path = c.get<std::filesystem::path>("path");
    plugin.parse(path, kType, kVersion, slotFor(path));
    if (plugin.getError().empty()) {
        const std::vector<float> values = plugin.packValues();
        params.insert(params.end(), values.begin(), values.end());
    }
}

void SkyTable::generateDispatch() {
    ShaderPlugin* active = nullptr;
    for (ShaderPlugin* plugin : ShaderPlugin::registry()) {
        if (plugin->getType() != SkyTable::kType) continue;
        if (!plugin->getError().empty() || plugin->getBody().empty()) continue;
        active = plugin;
        break;
    }

    std::string body = active
        ? std::format(
            "// ============================= {} =============================\n"
            "{}"
            "{}"
            "vec3 dispatchSky(int base, vec3 dir) {{\n"
            "{}"
            "vec3 result = vec3(0.1);\n"
            "{}"
            "return result;\n"
            "}}\n",
            SkyTable::kType, GlslCodegen::declareGlobals(*active), active->getDeclarations(),
            GlslCodegen::assignParams(*active, [](int i) { return std::format("pluginParams.values[base+{}]", i); }),
            active->getBody()
        )
        : "vec3 dispatchSky(int base, vec3 dir) {\n    return vec3(0.1);\n}\n";

    std::string content = std::format(
        "// WARN: AUTO-GENERATED by SkyTable::generateDispatch, do not edit by hand.\n"
        "// Source: the programmable sky script on the scene's Environment entity (see assets/environment/).\n"
        "{}",
        body
    );

    std::filesystem::path outputPath = "./src/shaders/generated/sky_dispatch.glsl";
    std::error_code ec;
    std::filesystem::create_directories(outputPath.parent_path(), ec);

    std::ifstream existing(outputPath);
    std::stringstream existingBuffer;
    existingBuffer << existing.rdbuf();
    if (existingBuffer.str() == content) return;

    std::ofstream(outputPath) << content;
}
